### ISSUE TITLE
Dependencies and depreciations

### ISSUE THREAD

**Issue by tobias-fritz** [evabertalan/cgraphs#19]
Hi, 

I was really intrigued by your tool for hydrogen bond mapping and wanted to try it out myself.
However, since there is no configuration file for the conda environment I am running into issues with dependencies and depreciations (such as np.int which is depreciated in numpy 1.24.3). Downgrading individual packages leads to more issues. Could you please provide a .yml file of your original working environment.

Thank you.

**Comment by evabertalan** [comment]
Hi,
thank you for reporting the issue!
The environment contains a lot of unrelated packages, so I left only the relevant packages and their versions in the .yml file (and converted to .txt so it is possible to attach it to a comment here in github).

[cgraphs_env.txt](https://github.com/evabertalan/cgraphs/files/12064390/cgraphs_env.txt)

Let me know if you encounter any further issues and I will work on a package update in the future.
